apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  # TODO: Validate name is being passed properly to the NIM runtime startup command
  name: mistral-7b-instruct
  annotations:
    nim_model_name: "trt_llm" # The name of the unpacked model
    autoscaling.knative.dev/target: "10" # Enable auto-scaling, set max queue size to 10 per NIM Pod
spec:
  predictor:
    minReplicas: 0 # Enable scale-to-zero
    # INFO: Use the right nodeSelector for the GPU label available in your cluster, check this with 'kubectl describe nodes'
    nodeSelector:
      # k8s.amazonaws.com/accelerator: "nvidia-tesla-t4"
      nvidia.com/gpu.product: A100-SXM4-80GB
    model:
      modelFormat:
        name: nvidia-nim-llm 
      # INFO: Update the 'nim-pvc' value to the name of the PVC created
      storageUri: "pvc://nim-pvc/model-store/mistral-7b-instruct_vMISTRAL-7b-INSTRUCT-1-A100.24.01/model-store"
      # INFO: at authorship the latest NIM model was built for 24.01, update this based of the tag of the model downloaded from NGC
      runtime: nvidia-nim-llm-24.01
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1